"""Configuration for the US stock screener."""

MIN_PRICE = 10
MIN_MARKET_CAP = 500_000_000
MIN_AVG_VOLUME = 500_000
MIN_ADR_PCT = 1
MAX_ADR_PCT = 10
MAX_ABOVE_10EMA_PCT = 15
MAX_ABOVE_20EMA_PCT = 20
MAX_DISTANCE_FROM_HIGH_PCT = 35
TOP_N = 15
CATEGORY_LIMIT = 20
MAX_PER_INDUSTRY = 3
MAX_PER_SECTOR = 5
MAX_WATCH_ONLY = 3
MAX_EXTENDED_NEAR_EMA = 2
MAX_WEAK_BREAKOUT = 3
DOWNLOAD_CHUNK_SIZE = 100
UNIVERSE_REFRESH_DAYS = 7
MIN_RS_SCORE = 60
PREFERRED_RS_SCORE = 80
MIN_VALID_UNIVERSE_COUNT = 1500
MIN_DOWNLOAD_SUCCESS_RATE = 0.70
YAHOO_DOWNLOAD_TIMEOUT_SECONDS = 20
MAX_DOWNLOAD_ATTEMPTS = 3
MAX_SCREENER_RUNTIME_SECONDS = 1800
DATA_TEST_MAX_RUNTIME_SECONDS = 120
DATA_TEST_TICKER_LIMIT = 20
MARKET_RETRY_DELAYS_SECONDS = [10, 30, 60]
HISTORY_RETRY_DELAYS_SECONDS = [2, 5]
FALLBACK_CHUNK_SIZES = [25, 10]

ENABLE_AI_COMMENTARY = True
AI_MODEL = "gpt-4o-mini"
AI_MAX_TICKERS = 15
AI_MAX_OUTPUT_TOKENS = 1200
AI_TEMPERATURE = 0.2
DEBUG = False
EMAIL_ENABLED = True

UNIVERSE_CSV = "universe.csv"
NASDAQ_LISTED_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"
OTHER_LISTED_URL = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"
